### ISSUE TITLE
__pycache__はgitリポジトリに含めるべきでない

### ISSUE THREAD

**Issue by sh1ma** [geek-space-hq/forumannounce-bot#1]
__pycache__はgitリポジトリに含めるべきでないので、.gitignoreを使ってgitにトラックされないようにするべきだと思います

**Comment by GS-Bacon** [comment]
.gitignore書いてみた

**Comment by sh1ma** [comment]
#2 で既存のファイルも削除しておきました！

**Comment by chun37** [comment]
.gitignore を作るときは、 https://github.com/github/gitignore とかを参考にすると良いかも

**Comment by GS-Bacon** [comment]
ありがと♡
